import Foundation
import SVNCore

enum RepositoryQueryTests {
    static func run() async throws {
        expectEqual(MergeEndpoints.displayName(for: "/sample/Branch/Dev", fallback: "源目录"), "Dev")
        expectEqual(MergeEndpoints.displayName(for: "/sample/Branch/Release/", fallback: "目标目录"), "Release")
        expectEqual(MergeEndpoints.displayName(for: #"C:\SVN\Branch\Develop"#, fallback: "源目录"), "Develop")
        expectEqual(MergeEndpoints.displayName(for: "/", fallback: "源目录"), "源目录")
        expectEqual(MergeEndpoints.displayName(for: "", fallback: "目标目录"), "目标目录")
        expectEqual(MergeEndpoints.direction(sourcePath: "/wc/Develop", targetPath: "/wc/Stable"), "Develop → Stable")
        print("PASS: merge endpoint names follow configured macOS and Windows paths")
        expectEqual(WorkspaceScope.includes(relative: "Assets/Code/file.cs", directory: "Assets", isDirectory: false, state: .modified, recursive: false), true)
        expectEqual(WorkspaceScope.includes(relative: "Assets/Code", directory: "Assets", isDirectory: true, state: .modified, recursive: false), true)
        expectEqual(WorkspaceScope.includes(relative: "Assets", directory: "Assets", isDirectory: true, state: .modified, recursive: false), true)
        expectEqual(WorkspaceScope.includes(relative: "", directory: "", isDirectory: true, state: .modified, recursive: false), true)
        expectEqual(WorkspaceScope.includes(relative: "AssetsOther/a", directory: "Assets", isDirectory: false, state: .added, recursive: true), false)
        expectEqual(WorkspaceScope.includes(relative: "Assets/Code/file.cs", directory: "Assets", isDirectory: false, state: .normal, recursive: false), false)
        print("PASS: recursive changes, directory properties, root and sibling boundary")
        var progress = UpdateTracker()
        let output = Data("Updating working copy:\nU    中文.cs\n A   props.txt\nU    中文.cs\nUpdated to revision 42.".utf8)
        for byte in output { progress.append(Data([byte])) }
        progress.finish()
        expectEqual(progress.count, 2)
        expectEqual(progress.detail, "Updated to revision 42.")
        print("PASS: streamed update paths, split UTF-8 and final output")
        let statusXML = """
        <status><target path="/wc"><entry path="/wc/Assets/A/a.cs"><wc-status item="modified" props="none"/></entry><entry path="/wc/Assets/A/new.cs"><wc-status item="added" props="none"/></entry><entry path="/wc/Assets/B/b.cs"><wc-status item="conflicted" props="none"/></entry><entry path="/wc/Docs"><wc-status item="normal" props="modified"/></entry><entry path="/wc/clean"><wc-status item="normal" props="none"/></entry></target></status>
        """
        let summary = DirectoryChanges.summarize(try WorkingCopyStatus.parse(Data(statusXML.utf8), root: "/wc"), directories: ["Assets", "Assets/A", "Assets/B", "Docs"])
        expectEqual(summary[""]?.count, 4)
        expectEqual(summary["Assets"]?.count, 3)
        expectEqual(summary["Assets"]?.state, .conflicted)
        expectEqual(summary["Assets/A"]?.state, .modified)
        expectEqual(summary["Docs"]?.state, .modified)
        expectEqual(DirectoryChanges.summarize([], directories: ["Assets"]).count, 0)
        print("PASS: ancestor change badges, conflict priority, directory properties and clearing")
        let luaOld = "-- generated\nlocal data = {[4] = {[1] = {DropId = {10, 20}, ScanCost = {{50001, 500}}, level = 1}, [2] = {level = 2}}}\nreturn data\n"
        let luaNew = "-- generated\nlocal data = {[4] = {[1] = {DropId = {10, 20, 30}, ScanCost = nil, level = 1}, [3] = {level = 3}}}\nreturn data\n"
        let structured = FileComparison(old: luaOld, new: luaNew, baseLabel: "BASE", ignoresIndentation: true, expandsLua: true)
        expectEqual(structured.luaLayoutUnavailable, false)
        expectEqual(structured.rows.contains { $0.oldText.contains("DropId") && $0.newText.contains("DropId") && $0.changed }, true)
        expectEqual(structured.rows.filter { $0.oldText.contains("ScanCost") }.first?.oldNumber, 2)
        expectEqual(structured.rows.filter { $0.oldText.contains("ScanCost") }.first?.newText.contains("nil"), true)
        expectEqual(structured.maximumLineLength < 100, true)
        expectEqual(structured.expandingLua(false).rows.compactMap { $0.oldNumber == nil ? nil : $0.oldText }.joined(separator: "\n") + "\n", luaOld)
        expectEqual(LuaComparisonLayout.expand("return {text = \"{,--}\", value = a - -b, same = a == b}")?.text.contains("a - -b"), true)
        expectEqual(LuaComparisonLayout.expand("return {text = \"{,--}\", value = a - -b, same = a == b}")?.text.contains("a == b"), true)
        expectEqual(LuaComparisonLayout.expand("return {text = [=[one\ntwo]=]}") == nil, true)
        expectEqual(LuaComparisonLayout.expand("return {text = \"unterminated}") == nil, true)
        expectEqual(LuaComparisonLayout.expand("return {value = 1") == nil, true)
        expectEqual(LuaComparisonLayout.expand("return {value = fn(1}") == nil, true)
        expectEqual(LuaComparisonLayout.expand("return {text = [=[{,}]=]}")?.text.contains("[=[{,}]=]"), true)
        expectEqual(FileComparison(old: "", new: "", baseLabel: "", expandsLua: true).rows.isEmpty, true)
        expectEqual(FileComparison(old: "\n \t\n", new: "", baseLabel: "", expandsLua: true).rows.isEmpty, true)
        expectEqual(FileComparison(old: "\n", new: "return {}\n", baseLabel: "", expandsLua: true).rows.first?.newNumber, 1)
        print("PASS: Lua display expansion, original lines, arrays, operators, literal protection and raw round trip")
        let aligned = FileComparison.align(old: "one\nold\nthree\n", new: "one\nnew\nextra\nthree\n")
        expectEqual(aligned.filter { $0.oldNumber != nil }.map(\.oldText), ["one", "old", "three"])
        expectEqual(aligned.filter { $0.newNumber != nil }.map(\.newText), ["one", "new", "extra", "three"])
        expectEqual(aligned.last?.oldNumber, 3)
        expectEqual(aligned.last?.newNumber, 4)
        expectEqual(FileComparison.align(old: "", new: "new").first?.oldNumber, nil)
        expectEqual(FileComparison(old: "x", new: "x\n", baseLabel: "").lineEndingChange, true)
        expectEqual(FileComparison(old: "", new: "", baseLabel: "").identical, true)
        print("PASS: complete comparison alignment and final newline")
        let indented = "return {\n    [1] = {\n        x = 1,\n        y = 2\n    },\n    [2] = {x = 9}\n}\n"
        let unindented = "return {\n[1] = {\nx = 3,\ny = 2\n},\n[2] = {x = 9}\n}\n"
        let readable = FileComparison(old: indented, new: unindented, baseLabel: "", ignoresIndentation: true)
        expectEqual(readable.rows.count, 7)
        expectEqual(readable.rows.filter(\.changed).count, 1)
        expectEqual(readable.rows.filter(\.changed).first?.oldNumber, 3)
        expectEqual(readable.rows.map(\.oldText).joined(separator: "\n") + "\n", indented)
        expectEqual(readable.ignoringIndentation(false).rows.filter(\.changed).count > 1, true)
        let literal = FileComparison(old: "return [=[\n  text\n]=]", new: "return [=[\ntext\n]=]", baseLabel: "", ignoresIndentation: true)
        expectEqual(literal.rows.contains(where: \.changed), true)
        expectEqual(FileComparison(old: "  x=1\n", new: "x=1\n", baseLabel: "", ignoresIndentation: true).formattingOnly, true)
        print("PASS: indentation comparison retains raw lines, exact mode and Lua string content")
        let recordsOld = "return {\n[10] = {[1] = {GroupID = 10, ItemNumMax = 12, ItemProbability = 3125}},\n[20] = {[1] = {GroupID = 20, ItemNumMax = 2}},\n[30] = {[1] = {GroupID = 30, ItemNumMax = 4}},\n}\n"
        let recordsNew = "return {\n[5] = {[1] = {GroupID = 5, ItemNumMax = 1}},\n[10] = {[1] = {GroupID = 10, ItemNumMax = 15, ItemProbability = 6250}},\n[30] = {[1] = {GroupID = 30, ItemNumMax = 8}},\n}\n"
        let recordComparison = FileComparison(old: recordsOld, new: recordsNew, baseLabel: "", ignoresIndentation: true)
        expectEqual(recordComparison.rows.count, 6)
        let paired = recordComparison.rows.first { $0.oldNumber == 2 }!
        expectEqual(paired.newNumber, 3)
        expectEqual(recordComparison.rows.first { $0.oldNumber == 3 }?.newNumber, nil)
        expectEqual(recordComparison.rows.first { $0.newNumber == 2 }?.oldNumber, nil)
        expectEqual(recordComparison.rows.filter { $0.oldNumber != nil }.map(\.oldText).joined(separator: "\n") + "\n", recordsOld)
        expectEqual(recordComparison.rows.filter { $0.newNumber != nil }.map(\.newText).joined(separator: "\n") + "\n", recordsNew)
        expectEqual(paired.fieldChanges.map(\.name), ["ItemNumMax", "ItemProbability"])
        expectEqual(paired.inline.oldRanges.map { (paired.oldText as NSString).substring(with: $0) }, ["12", "3125"])
        expectEqual(paired.inline.newRanges.map { (paired.newText as NSString).substring(with: $0) }, ["15", "6250"])
        let unicodeFields = FileComparison.align(old: #"[1] = {Name = "中文😀, fake = 2", Count = 12}"#, new: #"[1] = {Name = "中文😀, fake = 3", Count = 15}"#, ignoresIndentation: true)[0]
        expectEqual(unicodeFields.fieldChanges.map(\.name), ["Name", "Count"])
        expectEqual(unicodeFields.inline.newRanges.map { (unicodeFields.newText as NSString).substring(with: $0) }, [#""中文😀, fake = 3""#, "15"])
        let duplicateFields = FileComparison.align(old: "[1] = {{x = 1}, {x = 2}}", new: "[1] = {{x = 3}, {x = 4}}", ignoresIndentation: true)[0]
        expectEqual(duplicateFields.fieldChanges.count, 0)
        let moved = FileComparison.align(old: "[1] = {x = 1}\n[2] = {x = 2}", new: "[2] = {x = 3}\n[1] = {x = 4}", ignoresIndentation: true)
        expectEqual(moved.filter { $0.oldNumber != nil && $0.newNumber != nil }.allSatisfy { $0.oldText.prefix(3) == $0.newText.prefix(3) }, true)
        print("PASS: keyed Lua record alignment, additions/deletions/reordering, complete scalar highlights and Unicode summaries")
        let inline = InlineComparison(old: "中文😀 value=12; same; flag=0", new: "中文😀 value=34; same; flag=1")
        let oldInline = "中文😀 value=12; same; flag=0" as NSString
        let newInline = "中文😀 value=34; same; flag=1" as NSString
        expectEqual(inline.oldRanges.map { oldInline.substring(with: $0) }, ["12", "0"])
        expectEqual(inline.newRanges.map { newInline.substring(with: $0) }, ["34", "1"])
        expectEqual(InlineComparison(old: "abc", new: "abc+").oldRanges.count, 0)
        expectEqual(InlineComparison(old: "abc", new: "abc+").newRanges, [NSRange(location: 3, length: 1)])
        let folding = FileComparison(old: "a\nb\nc\nd\ne\n", new: "a\nb\nchanged\nd\ne\n", baseLabel: "")
        expectEqual(folding.displayLines(mode: 1), [.folded(0..<2), .row(2), .folded(3..<5)])
        expectEqual(folding.displayLines(mode: 1, expanded: [0]), [.row(0), .row(1), .row(2), .folded(3..<5)])
        expectEqual(folding.displayLines(mode: 1, context: 1), [.folded(0..<1), .row(1), .row(2), .row(3), .folded(4..<5)])
        expectEqual(folding.displayLines(mode: 2), [.row(0), .row(1), .folded(2..<3), .row(3), .row(4)])
        expectEqual(folding.displayLines(mode: 0), (0..<5).map { .row($0) })
        print("PASS: Unicode inline edits, insertion, difference folding, context and expansion")

        let xml = """
        <log><logentry revision="42"><author>a&amp;b</author><date>2026-09-05T10:20:30.123456Z</date><paths><path action="A" copyfrom-path="/old &amp; one" copyfrom-rev="40">/new@file</path><path action="D">/old</path></paths><msg>first line
        second &lt;line&gt;</msg></logentry></log>
        """
        let records = try RepositoryXML.history(Data(xml.utf8))
        expectEqual(records[0].paths[0].copyFrom, "/old & one")
        expectEqual(records[0].paths[0].copyRevision, "40")
        expectEqual(records[0].message, "first line\nsecond <line>")
        expectEqual(records[0].author, "a&b")
        expectEqual(records[0].date, "2026-09-05T10:20:30.123456Z")
        print("PASS: history lineage and XML text")
        expectThrows(try RepositoryXML.history(Data("<log>".utf8)))
        expectThrows(try RepositoryXML.entries(Data("<status/>".utf8)))
        expectEqual(try RepositoryXML.entries(Data("<lists/>".utf8)).count, 0)
        print("PASS: empty and malformed query responses")

        let base = FileManager.default.temporaryDirectory.appendingPathComponent("svn-query-" + UUID().uuidString)
        try FileManager.default.createDirectory(at: base, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: base) }
        let leftFile = base.appendingPathComponent("Release.txt"), rightFile = base.appendingPathComponent("candidate.txt")
        try Data("before\n".utf8).write(to: leftFile)
        try Data("after\n".utf8).write(to: rightFile)
        let pair = ComparisonFiles(old: leftFile.path, new: rightFile.path, oldLabel: "Release SVN · r42", newLabel: "待合入")
        let reviewed = try await RepositoryQuery().compareFiles(pair)
        expectEqual(reviewed.baseLabel, "Release SVN · r42")
        expectEqual(reviewed.rows.first?.oldText, "before")
        expectEqual(reviewed.rows.first?.newText, "after")
        let stagedAddition = try await RepositoryQuery().compareFiles(ComparisonFiles(old: nil, new: rightFile.path, oldLabel: "不存在", newLabel: "新增"))
        expectEqual(stagedAddition.rows.first?.oldNumber, nil)
        let stagedDeletion = try await RepositoryQuery().compareFiles(ComparisonFiles(old: leftFile.path, new: nil, oldLabel: "Release", newLabel: "删除"))
        expectEqual(stagedDeletion.rows.first?.newNumber, nil)
        print("PASS: staged file sources reuse text comparisons, labels and absent sides")
        let largeLeft = base.appendingPathComponent("large-left.lua")
        let largeRight = base.appendingPathComponent("large-right.lua")
        let largeLines = (0..<22_051).map { "config[\($0)] = {value = \($0)}" }
        var changedLargeLines = largeLines
        changedLargeLines[20_000] = "config[20000] = {value = 42}"
        try largeLines.joined(separator: "\n").write(to: largeLeft, atomically: true, encoding: .utf8)
        try changedLargeLines.joined(separator: "\n").write(to: largeRight, atomically: true, encoding: .utf8)
        let largeTextComparison = try await RepositoryQuery().compareFiles(
            ComparisonFiles(old: largeLeft.path, new: largeRight.path, oldLabel: "BASE", newLabel: "工作副本")
        )
        expectEqual(largeTextComparison.rows.count, 22_051)
        expectEqual(largeTextComparison.changeStarts, [20_000])
        expectEqual(largeTextComparison.rows[20_000].oldText, "config[20000] = {value = 20000}")
        expectEqual(largeTextComparison.rows[20_000].newText, "config[20000] = {value = 42}")
        print("PASS: text comparison supports files beyond 20,000 lines")
        let svn = ["/opt/homebrew/bin/svn", "/usr/local/bin/svn", "/usr/bin/svn"].first { FileManager.default.isExecutableFile(atPath: $0) }!
        let admin = (svn as NSString).deletingLastPathComponent + "/svnadmin"
        func run(_ path: String, _ args: [String]) throws { _ = try CommandRunner().run(executable: URL(fileURLWithPath: path), arguments: args).checked() }
        let repo = base.appendingPathComponent("repo"), wc = base.appendingPathComponent("wc")
        try run(admin, ["create", repo.path]); try run(svn, ["checkout", repo.absoluteString, wc.path])
        let large = wc.appendingPathComponent("large.lua")
        let luaLines = (0..<6000).map { "config[\($0)] = \"" + String(repeating: "value", count: 150) + "\"" }
        try luaLines.joined(separator: "\n").write(to: large, atomically: true, encoding: .utf8)
        let largeComparison = try await RepositoryQuery().compareFile(large.path)
        expectEqual(largeComparison.rows.count, 6000)
        expectEqual(largeComparison.rows.last?.newText, luaLines.last)
        expectEqual(largeComparison.changeStarts, [0])
        expectEqual(largeComparison.maximumLineLength, luaLines.last!.count)
        try FileManager.default.removeItem(at: large)
        print("PASS: 4 MB Lua with 6000 lines and cached navigation metadata")
        let file = wc.appendingPathComponent("space @ 中文.txt")
        try "version one".write(to: file, atomically: true, encoding: .utf8)
        try run(svn, ["add", file.path + "@"]); try run(svn, ["commit", wc.path, "-m", "first"])
        try "version two".write(to: file, atomically: true, encoding: .utf8)
        let localeDiff = try CommandRunner().run(executable: URL(fileURLWithPath: svn), arguments: ["diff", "--", file.path], environment: ["PATH": "/usr/bin:/bin", "LANG": "zh_CN.UTF-8", "LC_CTYPE": "C", "LC_MESSAGES": "zh_CN.UTF-8", "LANGUAGE": "zh_CN"]).checked()
        expectEqual(localeDiff.outputText.contains("+version two"), true)
        expectEqual(localeDiff.outputText.contains("{U+"), false)
        let localComparison = try await RepositoryQuery().compareFile(file.path)
        let statusData = try CommandRunner().run(executable: URL(fileURLWithPath: svn), arguments: ["status", "--xml", "--verbose", "--", wc.path + "@"]).checked().standardOutput
        let catalog = WorkspaceCatalog.build(root: wc.path, status: try WorkingCopyStatus.parse(statusData, root: wc.path))
        let listing = WorkspaceListingIndex(catalog).list(directory: "", recursive: false, unchanged: false, unversioned: true, filter: "")
        expectEqual(listing.shown.map(\.name), [file.lastPathComponent])
        expectEqual(listing.scopedCount, 1)
        expectEqual(WorkspaceListingIndex(catalog).list(directory: "other", recursive: true, unchanged: true, unversioned: true, filter: "").scopedCount, 0)
        print("PASS: catalog and indexed listing on real working copy")
        expectEqual(localComparison.rows.first?.oldText, "version one")
        expectEqual(localComparison.rows.first?.newText, "version two")
        expectEqual(localComparison.identical, false)
        try run(svn, ["commit", wc.path, "-m", "second"])
        expectEqual(try await RepositoryQuery().compareFile(file.path).identical, true)
        let added = wc.appendingPathComponent("new.txt")
        try "added".write(to: added, atomically: true, encoding: .utf8)
        expectEqual(try await RepositoryQuery().compareFile(added.path).rows.first?.oldNumber, nil)
        try FileManager.default.removeItem(at: added)
        print("PASS: working BASE, modified, unchanged and unversioned comparison")
        try run(svn, ["delete", file.path + "@"]); let deleted = try await RepositoryQuery().compareFile(file.path)
        expectEqual(deleted.rows.first?.oldText, "version two")
        expectEqual(deleted.rows.first?.newNumber, nil)
        try run(svn, ["commit", wc.path, "-m", "delete"])
        let query = RepositoryQuery(), url = repo.appendingPathComponent(file.lastPathComponent).absoluteString
        let old = try await query.list(repo.absoluteString, revision: "1")
        expectEqual(old.first?.name, file.lastPathComponent)
        expectEqual(try await query.content(url, revision: "1"), "version one")
        expectEqual(try await query.content(url, revision: "2"), "version two")
        expectEqual(try await query.list(repo.absoluteString, revision: "3").count, 0)
        let remote = try await query.compareRepositoryFile(url, revision: "2")
        expectEqual(remote.rows.first?.oldText, "version one")
        expectEqual(remote.rows.first?.newText, "version two")
        expectEqual(try await query.compareRepositoryFile(url, revision: "1").rows.first?.oldNumber, nil)
        let history = try await query.history(url, peg: "2", start: "2")
        expectEqual(history.map(\.revision), ["2", "1"])
        expectEqual(try await query.history(url, peg: "2", start: "1").map(\.revision), ["1"])
        print("PASS: real historical listing, deleted file preview, peg history and special paths")
        func selectedChange(_ revision: String, path: String) async throws -> ChangedPath {
            let records = try await query.history(repo.absoluteString, peg: revision, start: revision)
            return records[0].paths.first { $0.path == path }!
        }
        let repositoryPath = "/" + file.lastPathComponent
        let modifiedEntry = try await selectedChange("2", path: repositoryPath)
        expectEqual(modifiedEntry.kind, "file")
        let selected = try await query.compareRepositoryFile(url, revision: "2", change: modifiedEntry)
        expectEqual(selected.rows.first?.oldText, "version one")
        expectEqual(selected.rows.first?.newText, "version two")
        let deletedEntry = try await selectedChange("3", path: repositoryPath)
        let historicalDeletion = try await query.compareRepositoryFile(url, revision: "3", change: deletedEntry)
        expectEqual(historicalDeletion.rows.first?.oldText, "version two")
        expectEqual(historicalDeletion.rows.first?.newNumber, nil)
        let addedEntry = try await selectedChange("1", path: repositoryPath)
        expectEqual(try await query.compareRepositoryFile(url, revision: "1", change: addedEntry).rows.first?.oldNumber, nil)
        let copy = wc.appendingPathComponent("copy @ 中文.txt")
        try run(svn, ["copy", url + "@2", copy.path + "@"])
        try "copied and edited".write(to: copy, atomically: true, encoding: .utf8)
        try run(svn, ["commit", wc.path, "-m", "copy"])
        let copyEntry = try await selectedChange("4", path: "/" + copy.lastPathComponent)
        let copied = try await query.compareRepositoryFile(repo.appendingPathComponent(copy.lastPathComponent).absoluteString, revision: "4", change: copyEntry)
        expectEqual(copied.rows.first?.oldText, "version two")
        expectEqual(copied.rows.first?.newText, "copied and edited")
        print("PASS: selected commit modification, addition, deletion and edited copy with special paths")

    }
}
