import AppKit
import SwiftUI

enum AppIdentity {
    static var name: String { Bundle.main.object(forInfoDictionaryKey: "CFBundleDisplayName") as? String ?? "提交合并分支工具" }
    static var version: String { Bundle.main.object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String ?? "开发版" }
    static var build: String { Bundle.main.object(forInfoDictionaryKey: "CFBundleVersion") as? String ?? "未打包" }
    static var title: String { "\(name) v\(version) (\(build))" }
}

enum InterfaceLanguage {
    static let key = "SvnFlow.interfaceLanguage"
    static var code: String { UserDefaults.standard.string(forKey: key) == "en" ? "en" : "zh-Hans" }
    @MainActor static func select(_ code: String) {
        UserDefaults.standard.set(code, forKey: key)
        for window in NSApp.windows { window.title = localizedWindowTitle(window.title) }
        DispatchQueue.main.async { localizeSystemMenus() }
    }
}
func L(_ source: String) -> String {
    guard let pair = InterfaceText.values[source] else { return source }
    return InterfaceLanguage.code == "en" ? pair.0 : pair.1
}
private enum InterfaceText {
    static let values: [String: (String, String)] = [
        "A working copy will be created in the selected directory": ("A working copy will be created in the selected directory", "将在所选目录内创建工作副本"),
        "Action": ("Action", "操作"),
        "Add": ("Add", "添加"),
        "Add Working Copy": ("Add Working Copy", "添加工作副本"),
        "Add unversioned files to version control first": ("Add unversioned files to version control first", "请先将未纳入版本的文件加入版本控制"),
        "Added": ("Added", "待新增"),
        "Adding to version control…": ("Adding to version control…", "加入版本控制…"),
        "Align by worksheet name and cell address": ("Align by worksheet name and cell address", "按工作表名称和单元格地址对齐"),
        "Aligned by address · Formatting and images excluded": ("Aligned by address · Formatting and images excluded", "按地址对齐 · 不比较格式和图片"),
        "All": ("All", "全部"),
        "All Changed Paths": ("All Changed Paths", "全部变更路径"),
        "Annotate": ("Annotate", "逐行追溯"),
        "Annotating…": ("Annotating…", "逐行追溯…"),
        "Author": ("Author", "作者"),
        "Background verification · Full status pending": ("Background verification · Full status pending", "后台校验中 · 完整状态待校准"),
        "Base Revision": ("Base Revision", "基础版本"),
        "Branch": ("Branch", "分支"),
        "Bring All to Front": ("Bring All to Front", "全部前置"),
        "Cancel": ("Cancel", "取消"),
        "Cannot preview": ("Cannot preview", "无法预览"),
        "Change Set": ("Change Set", "变更集"),
        "Changed Paths — entire commit": ("Changed Paths — entire commit", "变更路径 — 整次提交"),
        "Changes": ("Changes", "差异"),
        "Check Out Working Copy": ("Check Out Working Copy", "检出工作副本"),
        "Check Out…": ("Check Out…", "检出…"),
        "Check for Modifications": ("Check for Modifications", "检查改动"),
        "Checking out…": ("Checking out…", "正在检出…"),
        "Choose Parent Directory": ("Choose Parent Directory", "选择父目录"),
        "Clean Up": ("Clean Up", "清理"),
        "Cleaning up working copy…": ("Cleaning up working copy…", "清理工作副本…"),
        "Clear Output": ("Clear Output", "清空输出"),
        "Close Project": ("Close Project", "关闭项目"),
        "Close Window": ("Close Window", "关闭窗口"),
        "Commit": ("Commit", "提交"),
        "Commit Message": ("Commit Message", "提交说明"),
        "Commit…": ("Commit…", "提交…"),
        "Compare with Base": ("Compare with Base", "与基础版本比较"),
        "Compare — ": ("Compare — ", "比较 — "),
        "Confirm": ("Confirm", "确认"),
        "Conflicted": ("Conflicted", "有冲突"),
        "Continue": ("Continue", "继续"),
        "Copy": ("Copy", "复制"),
        "Copy From": ("Copy From", "复制来源"),
        "Copy Message": ("Copy Message", "复制说明"),
        "Copy Path": ("Copy Path", "复制路径"),
        "Create Branch or Tag": ("Create Branch or Tag", "创建分支或标签"),
        "Create Branch or Tag…": ("Create Branch or Tag…", "创建分支或标签…"),
        "Cut": ("Cut", "剪切"),
        "Date": ("Date", "日期"),
        "Delete": ("Delete", "删除"),
        "Deselect All": ("Deselect All", "取消全选"),
        "Differences": ("Differences", "差别"),
        "Directories": ("Directories", "目录"),
        "Done": ("Done", "完成"),
        "Edit": ("Edit", "编辑"),
        "Enter Full Screen": ("Enter Full Screen", "进入全屏幕"),
        "Enter a commit message": ("Enter a commit message", "输入提交说明"),
        "Enter a new path relative to the working copy": ("Enter a new path relative to the working copy", "输入相对于工作副本的新路径"),
        "Enter a repository URL to browse": ("Enter a repository URL to browse", "输入仓库 URL 开始浏览"),
        "Enter a valid repository URL and HEAD or a nonnegative revision.": ("Enter a valid repository URL and HEAD or a nonnegative revision.", "请输入有效仓库 URL 和 HEAD 或非负修订号。"),
        "Enter an SVN repository URL": ("Enter an SVN repository URL", "输入 SVN 仓库 URL"),
        "Enter the destination repository URL to create a server-side copy of this working copy URL.": ("Enter the destination repository URL to create a server-side copy of this working copy URL.", "输入目标仓库 URL，将从当前工作副本地址执行服务器端复制。"),
        "Enter the target branch or tag URL. Commit or shelve local changes before switching.": ("Enter the target branch or tag URL. Commit or shelve local changes before switching.", "输入目标分支或标签 URL。执行前请先提交或搁置本地改动。"),
        "Exit Full Screen": ("Exit Full Screen", "退出全屏幕"),
        "External": ("External", "外部引用"),
        "File": ("File", "文件"),
        "File Filter": ("File Filter", "文件筛选"),
        "File Log": ("File Log", "文件日志"),
        "File name filter": ("File name filter", "按文件名筛选"),
        "Files": ("Files", "文件"),
        "Files are identical": ("Files are identical", "文件内容相同"),
        "Files remain on disk but will no longer be managed by SVN.": ("Files remain on disk but will no longer be managed by SVN.", "文件会保留在磁盘上，但不再受 SVN 管理。"),
        "Files will be deleted from the repository on the next commit.": ("Files will be deleted from the repository on the next commit.", "文件将在下次提交时从仓库删除。"),
        "Files — ": ("Files — ", "文件 — "),
        "Filter revisions, authors and messages": ("Filter revisions, authors and messages", "筛选修订号、作者和说明"),
        "Fix": ("Fix", "修复"),
        "Format": ("Format", "格式"),
        "Go": ("Go", "前往"),
        "Graph": ("Graph", "版本图"),
        "Help": ("Help", "帮助"),
        "Hide Current Directory and Descendants": ("Hide Current Directory and Descendants", "忽略当前目录及其子项"),
        "Hide Selected File": ("Hide Selected File", "忽略选中文件"),
        "Hide This Item (Local Display)": ("Hide This Item (Local Display)", "忽略此项（本地显示）"),
        "Hide files and directories in this app for the current working copy. Preferences persist after restart. Files, SVN properties and the repository remain unchanged. Directory rules include all descendants.": ("Hide files and directories in this app for the current working copy. Preferences persist after restart. Files, SVN properties and the repository remain unchanged. Directory rules include all descendants.", "仅在本应用中隐藏当前工作副本的文件和目录，重启后仍生效。不会修改文件、SVN 属性或仓库；目录规则包含全部子项。"),
        "Hide locally without changing SVN properties": ("Hide locally without changing SVN properties", "本地忽略显示，不修改 SVN 属性"),
        "Home": ("Home", "主页"),
        "Ignore formatting and images": ("Ignore formatting and images", "忽略格式与图片"),
        "Ignored": ("Ignored", "已忽略"),
        "Include Unchanged Files from Subdirectories — changes always include subdirectories": ("Include Unchanged Files from Subdirectories — changes always include subdirectories", "包含子目录中的未修改文件；变化始终包含子目录"),
        "Incomplete": ("Incomplete", "不完整"),
        "Interface Language": ("Interface Language", "界面语言"),
        "Language": ("Language", "语言"),
        "Language changes apply immediately and are remembered on this Mac.": ("Language changes apply immediately and are remembered on this Mac.", "切换立即生效，并在本机记住选择。"),
        "Large working copies may take a moment to load. Please wait.": ("Large working copies may take a moment to load. Please wait.", "大型工作副本加载需要一些时间，请稍候。"),
        "Load Older": ("Load Older", "加载更早记录"),
        "Loading SVN…": ("Loading SVN…", "正在加载 SVN…"),
        "Loading comparison…": ("Loading comparison…", "正在加载比较…"),
        "Loading…": ("Loading…", "正在加载…"),
        "Local State": ("Local State", "本地状态"),
        "Local directory name": ("Local directory name", "本地目录名称"),
        "Local preview": ("Local preview", "本地预览"),
        "Lock": ("Lock", "锁定"),
        "Locking files…": ("Locking files…", "锁定文件…"),
        "Locks": ("Locks", "锁定管理"),
        "Log": ("Log", "日志"),
        "Log…": ("Log…", "日志…"),
        "MS Excel Workbook": ("MS Excel Workbook", "MS Excel 工作簿"),
        "MS Excel 工作簿": ("MS Excel Workbook", "MS Excel 工作簿"),
        "Main": ("Main", "主视图"),
        "Main Perspective": ("Main Perspective", "主视图"),
        "Manage Hidden Items": ("Manage Hidden Items", "管理忽略项"),
        "Manage Hidden Items…": ("Manage Hidden Items…", "管理忽略项…"),
        "Many changes; scanning the update scope…": ("Many changes; scanning the update scope…", "变化较多，正在扫描更新范围…"),
        "Mark for Deletion?": ("Mark for Deletion?", "标记为删除？"),
        "Marking for deletion…": ("Marking for deletion…", "标记删除…"),
        "Merge": ("Merge", "合并"),
        "Merge source URL is required": ("Merge source URL is required", "请输入合并来源 URL"),
        "Merge…": ("Merge…", "合并…"),
        "Merging changes and refreshing the interface…": ("Merging changes and refreshing the interface…", "正在合并变化并刷新界面…"),
        "Merging…": ("Merging…", "执行合并…"),
        "Message": ("Message", "说明"),
        "Minimize": ("Minimize", "最小化"),
        "Minor": ("Minor", "次要"),
        "Missing": ("Missing", "本地缺失"),
        "Modified": ("Modified", "已修改"),
        "Modify": ("Modify", "修改"),
        "Move": ("Move", "移动"),
        "Move or Rename": ("Move or Rename", "移动或重命名"),
        "Move or Rename…": ("Move or Rename…", "移动或重命名…"),
        "Moving…": ("Moving…", "移动…"),
        "Name": ("Name", "名称"),
        "Next Change": ("Next Change", "下一处差异"),
        "Next Changed File": ("Next Changed File", "下一个变化文件"),
        "Next Difference": ("Next Difference", "下一个对比"),
        "No cell selected": ("No cell selected", "未选择单元格"),
        "No changes to commit": ("No changes to commit", "没有可提交的改动"),
        "No hidden items in this working copy": ("No hidden items in this working copy", "当前工作副本没有忽略项"),
        "No matching files": ("No matching files", "没有匹配的文件"),
        "No rows match the current filter": ("No rows match the current filter", "当前筛选下没有行"),
        "No unversioned files in the selection": ("No unversioned files in the selection", "所选内容中没有未纳入版本控制的文件"),
        "No working copy selected": ("No working copy selected", "未选择工作副本"),
        "Normal": ("Normal", "正常"),
        "OK": ("OK", "确定"),
        "Obstructed": ("Obstructed", "被阻挡"),
        "Open": ("Open", "打开"),
        "Open Working Copy…": ("Open Working Copy…", "打开工作副本…"),
        "Open a working copy to get started.": ("Open a working copy to get started.", "打开一个工作副本以开始使用。"),
        "Open in Repository Browser": ("Open in Repository Browser", "在仓库浏览器中打开"),
        "Open or check out an SVN working copy first": ("Open or check out an SVN working copy first", "请先打开或检出一个 SVN 工作副本"),
        "Operation Failed": ("Operation Failed", "操作失败"),
        "Organizing directories and file status…": ("Organizing directories and file status…", "正在整理目录和文件状态，请稍候…"),
        "Output": ("Output", "输出"),
        "Paste": ("Paste", "粘贴"),
        "Path": ("Path", "路径"),
        "Perform Merge?": ("Perform Merge?", "执行合并？"),
        "Please enter a commit message": ("Please enter a commit message", "请填写提交说明"),
        "Please open a working copy first": ("Please open a working copy first", "请先打开工作副本"),
        "Please select a file in the list first": ("Please select a file in the list first", "请先在文件列表中选择一个文件"),
        "Please select files first": ("Please select files first", "请先勾选文件"),
        "Previewing merge…": ("Previewing merge…", "预演合并…"),
        "Previous Change": ("Previous Change", "上一处差异"),
        "Previous Changed File": ("Previous Changed File", "上一个变化文件"),
        "Previous Difference": ("Previous Difference", "上一对比"),
        "Project": ("Project", "项目"),
        "Properties Modified": ("Properties Modified", "属性已修改"),
        "Query": ("Query", "查询"),
        "Read Only": ("Read Only", "只读"),
        "Read only · Editing disabled": ("Read only · Editing disabled", "｜只读 · 禁止编辑"),
        "Reading and comparing worksheets…": ("Reading and comparing worksheets…", "读取工作表并比较…"),
        "Reading file history…": ("Reading file history…", "读取文件历史…"),
        "Reading history…": ("Reading history…", "读取提交历史…"),
        "Reading properties…": ("Reading properties…", "读取属性…"),
        "Reading repository…": ("Reading repository…", "读取仓库…"),
        "Ready": ("Ready", "就绪"),
        "Redo": ("Redo", "重做"),
        "Refresh": ("Refresh", "刷新"),
        "Refresh Log": ("Refresh Log", "刷新日志"),
        "Relative Directory": ("Relative Directory", "相对目录"),
        "Reload": ("Reload", "重载"),
        "Reload Changes": ("Reload Changes", "重新加载差异"),
        "Remote State": ("Remote State", "远程状态"),
        "Remove": ("Remove", "移除"),
        "Remove from Version Control": ("Remove from Version Control", "从版本控制中移除"),
        "Remove from Version Control?": ("Remove from Version Control?", "从版本控制中移除？"),
        "Removed": ("Removed", "待删除"),
        "Removing from version control…": ("Removing from version control…", "移除版本控制…"),
        "Replaced": ("Replaced", "已替换"),
        "Repository": ("Repository", "仓库"),
        "Repository Browser": ("Repository Browser", "仓库浏览器"),
        "Repository URL": ("Repository URL", "仓库 URL"),
        "Repository source URL": ("Repository source URL", "仓库来源 URL"),
        "Repository · r": ("Repository · r", "仓库 · r"),
        "Resolving conflict…": ("Resolving conflict…", "解决冲突…"),
        "Restore All": ("Restore All", "全部恢复"),
        "Restore Display": ("Restore Display", "恢复显示"),
        "Retry loading": ("Retry loading", "重新加载"),
        "Reveal in Finder": ("Reveal in Finder", "在访达中显示"),
        "Revert": ("Revert", "撤销"),
        "Revert Selected Changes?": ("Revert Selected Changes?", "撤销所选改动？"),
        "Reverting changes…": ("Reverting changes…", "撤销改动…"),
        "Review": ("Review", "审阅"),
        "Review Perspective": ("Review Perspective", "审阅视图"),
        "Revision": ("Revision", "修订号"),
        "Revision Info": ("Revision Info", "修订信息"),
        "Revisions": ("Revisions", "修订记录"),
        "Rules": ("Rules", "规则"),
        "SVN Base Revision": ("SVN Base Revision", "SVN 基础版本"),
        "SVN Workbench": ("Commit and Branch Merge Tool", "提交合并分支工具"),
        "SVN 基础版本": ("SVN Base Revision", "SVN 基础版本"),
        "SVN 工作台": ("Commit and Branch Merge Tool", "提交合并分支工具"),
        "Same": ("Same", "相同"),
        "Scanning working copy…": ("Scanning working copy…", "扫描工作副本…"),
        "Select All": ("Select All", "全选"),
        "Select a file to view changes": ("Select a file to view changes", "选择文件查看差异"),
        "Select a revision": ("Select a revision", "选择一条修订记录"),
        "Session": ("Session", "会话"),
        "Settings…": ("Settings…", "设置…"),
        "Show Changes": ("Show Changes", "查看差异"),
        "Show Properties": ("Show Properties", "查看属性"),
        "Show Unchanged": ("Show Unchanged", "显示未修改项"),
        "Show Unchanged Files": ("Show Unchanged Files", "显示未修改文件"),
        "Show Unversioned Files": ("Show Unversioned Files", "显示未纳入版本的文件"),
        "Show formulas and cached results": ("Show formulas and cached results", "显示公式及缓存结果"),
        "Show or hide files without local changes": ("Show or hide files without local changes", "显示或隐藏没有本地改动的文件"),
        "Show rows differing only in leading or trailing whitespace": ("Show rows differing only in leading or trailing whitespace", "仅显示首尾空白不同的行"),
        "Side By Side": ("Side By Side", "并排比较"),
        "Size": ("Size", "大小"),
        "Swap": ("Swap", "交换"),
        "Switch Working Copy": ("Switch Working Copy", "切换工作副本"),
        "Switching working copy…": ("Switching working copy…", "切换工作副本…"),
        "Switch…": ("Switch…", "切换…"),
        "Synchronized scrolling": ("Synchronized scrolling", "左右同步滚动"),
        "Tag+Branch": ("Tag+Branch", "标签与分支"),
        "Text preview is unavailable for files larger than 1 MB.": ("Text preview is unavailable for files larger than 1 MB.", "文件超过 1 MB，暂不提供文本预览。"),
        "This directory has no textual or property differences. Select files in the list to compare descendants.": ("This directory has no textual or property differences. Select files in the list to compare descendants.", "该目录没有可显示的文本或属性差异。子项变化请在文件列表中选择。"),
        "This directory is empty": ("This directory is empty", "此目录为空"),
        "This discards local changes and cannot be undone.": ("This discards local changes and cannot be undone.", "此操作会丢弃本地修改，无法恢复。"),
        "This operation immediately creates a commit in the repository.": ("This operation immediately creates a commit in the repository.", "该操作会立即在仓库中创建一次提交。"),
        "Tools": ("Tools", "工具"),
        "Transactions": ("Transactions", "操作记录"),
        "UTF-8 · BASE ↔ Working Copy": ("UTF-8 · BASE ↔ Working Copy", "UTF-8 · 基础版本 ↔ 工作副本"),
        "UTF-8 · Previous ↔ Selected Revision": ("UTF-8 · Previous ↔ Selected Revision", "UTF-8 · 前一版本 ↔ 所选修订"),
        "UTF-8 · 前一版本 ↔ 所选修订": ("UTF-8 · Previous ↔ Selected Revision", "UTF-8 · 前一版本 ↔ 所选修订"),
        "UTF-8 · 基础版本 ↔ 工作副本": ("UTF-8 · BASE ↔ Working Copy", "UTF-8 · 基础版本 ↔ 工作副本"),
        "Undo": ("Undo", "撤销"),
        "Unified": ("Unified", "统一差异"),
        "Unknown": ("Unknown", "未知"),
        "Unknown author": ("Unknown author", "未知作者"),
        "Unknown error": ("Unknown error", "未知错误"),
        "Unlock": ("Unlock", "解锁"),
        "Unlocking files…": ("Unlocking files…", "解锁文件…"),
        "Unresolved conflicts prevent committing": ("Unresolved conflicts prevent committing", "存在未解决冲突，已阻止提交"),
        "Unversioned": ("Unversioned", "未纳入版本"),
        "Up": ("Up", "上一级"),
        "Update": ("Update", "更新"),
        "Update complete": ("Update complete", "更新完成"),
        "Update complete; refreshing affected files…": ("Update complete; refreshing affected files…", "更新完成，正在刷新受影响文件…"),
        "Update scope: ": ("Update scope: ", "更新范围："),
        "Updating ": ("Updating ", "更新 "),
        "View": ("View", "视图"),
        "Window": ("Window", "窗口"),
        "Working Copies": ("Working Copies", "工作副本"),
        "Working Copy": ("Working Copy", "工作副本"),
        "Working copy is clean": ("Working copy is clean", "工作副本干净"),
        "Zoom": ("Zoom", "缩放"),
        "上一个变化文件": ("Previous Changed File", "上一个变化文件"),
        "上一处差异": ("Previous Change", "上一处差异"),
        "上一对比": ("Previous Difference", "上一对比"),
        "上一级": ("Up", "上一级"),
        "下一个变化文件": ("Next Changed File", "下一个变化文件"),
        "下一个对比": ("Next Difference", "下一个对比"),
        "下一处差异": ("Next Change", "下一处差异"),
        "不完整": ("Incomplete", "不完整"),
        "与基础版本比较": ("Compare with Base", "与基础版本比较"),
        "主视图": ("Main", "主视图"),
        "主页": ("Home", "主页"),
        "交换": ("Swap", "交换"),
        "仅在本应用中隐藏当前工作副本的文件和目录，重启后仍生效。不会修改文件、SVN 属性或仓库；目录规则包含全部子项。": ("Hide files and directories in this app for the current working copy. Preferences persist after restart. Files, SVN properties and the repository remain unchanged. Directory rules include all descendants.", "仅在本应用中隐藏当前工作副本的文件和目录，重启后仍生效。不会修改文件、SVN 属性或仓库；目录规则包含全部子项。"),
        "仅显示首尾空白不同的行": ("Show rows differing only in leading or trailing whitespace", "仅显示首尾空白不同的行"),
        "从版本控制中移除": ("Remove from Version Control", "从版本控制中移除"),
        "从版本控制中移除？": ("Remove from Version Control?", "从版本控制中移除？"),
        "仓库": ("Repository", "仓库"),
        "仓库 URL": ("Repository URL", "仓库 URL"),
        "仓库 · r": ("Repository · r", "仓库 · r"),
        "仓库来源 URL": ("Repository source URL", "仓库来源 URL"),
        "仓库浏览器": ("Repository Browser", "仓库浏览器"),
        "会话": ("Session", "会话"),
        "作者": ("Author", "作者"),
        "修复": ("Fix", "修复"),
        "修改": ("Modify", "修改"),
        "修订信息": ("Revision Info", "修订信息"),
        "修订号": ("Revision", "修订号"),
        "修订记录": ("Revisions", "修订记录"),
        "全选": ("Select All", "全选"),
        "全部": ("All", "全部"),
        "全部前置": ("Bring All to Front", "全部前置"),
        "全部变更路径": ("All Changed Paths", "全部变更路径"),
        "全部恢复": ("Restore All", "全部恢复"),
        "关闭窗口": ("Close Window", "关闭窗口"),
        "关闭项目": ("Close Project", "关闭项目"),
        "分支": ("Branch", "分支"),
        "切换…": ("Switch…", "切换…"),
        "切换工作副本": ("Switch Working Copy", "切换工作副本"),
        "切换工作副本…": ("Switching working copy…", "切换工作副本…"),
        "切换立即生效，并在本机记住选择。": ("Language changes apply immediately and are remembered on this Mac.", "切换立即生效，并在本机记住选择。"),
        "创建分支或标签": ("Create Branch or Tag", "创建分支或标签"),
        "创建分支或标签…": ("Create Branch or Tag…", "创建分支或标签…"),
        "删除": ("Delete", "删除"),
        "刷新": ("Refresh", "刷新"),
        "刷新日志": ("Refresh Log", "刷新日志"),
        "前往": ("Go", "前往"),
        "剪切": ("Cut", "剪切"),
        "加入版本控制…": ("Adding to version control…", "加入版本控制…"),
        "加载更早记录": ("Load Older", "加载更早记录"),
        "包含子目录中的未修改文件；变化始终包含子目录": ("Include Unchanged Files from Subdirectories — changes always include subdirectories", "包含子目录中的未修改文件；变化始终包含子目录"),
        "取消": ("Cancel", "取消"),
        "取消全选": ("Deselect All", "取消全选"),
        "变化较多，正在扫描更新范围…": ("Many changes; scanning the update scope…", "变化较多，正在扫描更新范围…"),
        "变更路径 — 整次提交": ("Changed Paths — entire commit", "变更路径 — 整次提交"),
        "变更集": ("Change Set", "变更集"),
        "只读": ("Read Only", "只读"),
        "合并": ("Merge", "合并"),
        "合并…": ("Merge…", "合并…"),
        "名称": ("Name", "名称"),
        "后台校验中 · 完整状态待校准": ("Background verification · Full status pending", "后台校验中 · 完整状态待校准"),
        "在仓库浏览器中打开": ("Open in Repository Browser", "在仓库浏览器中打开"),
        "在访达中显示": ("Reveal in Finder", "在访达中显示"),
        "基础版本": ("Base Revision", "基础版本"),
        "复制": ("Copy", "复制"),
        "复制来源": ("Copy From", "复制来源"),
        "复制说明": ("Copy Message", "复制说明"),
        "复制路径": ("Copy Path", "复制路径"),
        "外部引用": ("External", "外部引用"),
        "大型工作副本加载需要一些时间，请稍候。": ("Large working copies may take a moment to load. Please wait.", "大型工作副本加载需要一些时间，请稍候。"),
        "大小": ("Size", "大小"),
        "存在未解决冲突，已阻止提交": ("Unresolved conflicts prevent committing", "存在未解决冲突，已阻止提交"),
        "完成": ("Done", "完成"),
        "审阅": ("Review", "审阅"),
        "审阅视图": ("Review Perspective", "审阅视图"),
        "将在所选目录内创建工作副本": ("A working copy will be created in the selected directory", "将在所选目录内创建工作副本"),
        "就绪": ("Ready", "就绪"),
        "属性已修改": ("Properties Modified", "属性已修改"),
        "工作副本": ("Working Copies", "工作副本"),
        "工作副本干净": ("Working copy is clean", "工作副本干净"),
        "工具": ("Tools", "工具"),
        "左右同步滚动": ("Synchronized scrolling", "左右同步滚动"),
        "差别": ("Differences", "差别"),
        "差异": ("Changes", "差异"),
        "已修改": ("Modified", "已修改"),
        "已忽略": ("Ignored", "已忽略"),
        "已替换": ("Replaced", "已替换"),
        "帮助": ("Help", "帮助"),
        "并排比较": ("Side By Side", "并排比较"),
        "当前工作副本没有忽略项": ("No hidden items in this working copy", "当前工作副本没有忽略项"),
        "当前筛选下没有行": ("No rows match the current filter", "当前筛选下没有行"),
        "待删除": ("Removed", "待删除"),
        "待新增": ("Added", "待新增"),
        "忽略当前目录及其子项": ("Hide Current Directory and Descendants", "忽略当前目录及其子项"),
        "忽略格式与图片": ("Ignore formatting and images", "忽略格式与图片"),
        "忽略此项（本地显示）": ("Hide This Item (Local Display)", "忽略此项（本地显示）"),
        "忽略选中文件": ("Hide Selected File", "忽略选中文件"),
        "恢复显示": ("Restore Display", "恢复显示"),
        "所选内容中没有未纳入版本控制的文件": ("No unversioned files in the selection", "所选内容中没有未纳入版本控制的文件"),
        "打开": ("Open", "打开"),
        "打开一个工作副本以开始使用。": ("Open a working copy to get started.", "打开一个工作副本以开始使用。"),
        "打开工作副本…": ("Open Working Copy…", "打开工作副本…"),
        "执行合并…": ("Merging…", "执行合并…"),
        "执行合并？": ("Perform Merge?", "执行合并？"),
        "扫描工作副本…": ("Scanning working copy…", "扫描工作副本…"),
        "按地址对齐 · 不比较格式和图片": ("Aligned by address · Formatting and images excluded", "按地址对齐 · 不比较格式和图片"),
        "按工作表名称和单元格地址对齐": ("Align by worksheet name and cell address", "按工作表名称和单元格地址对齐"),
        "按文件名筛选": ("File name filter", "按文件名筛选"),
        "提交": ("Commit", "提交"),
        "提交…": ("Commit…", "提交…"),
        "提交说明": ("Commit Message", "提交说明"),
        "撤销": ("Revert", "撤销"),
        "撤销所选改动？": ("Revert Selected Changes?", "撤销所选改动？"),
        "撤销改动…": ("Reverting changes…", "撤销改动…"),
        "操作": ("Action", "操作"),
        "操作失败": ("Operation Failed", "操作失败"),
        "操作记录": ("Transactions", "操作记录"),
        "文件": ("Files", "文件"),
        "文件 — ": ("Files — ", "文件 — "),
        "文件会保留在磁盘上，但不再受 SVN 管理。": ("Files remain on disk but will no longer be managed by SVN.", "文件会保留在磁盘上，但不再受 SVN 管理。"),
        "文件内容相同": ("Files are identical", "文件内容相同"),
        "文件将在下次提交时从仓库删除。": ("Files will be deleted from the repository on the next commit.", "文件将在下次提交时从仓库删除。"),
        "文件日志": ("File Log", "文件日志"),
        "文件筛选": ("File Filter", "文件筛选"),
        "文件超过 1 MB，暂不提供文本预览。": ("Text preview is unavailable for files larger than 1 MB.", "文件超过 1 MB，暂不提供文本预览。"),
        "无法预览": ("Cannot preview", "无法预览"),
        "日志": ("Log", "日志"),
        "日志…": ("Log…", "日志…"),
        "日期": ("Date", "日期"),
        "显示公式及缓存结果": ("Show formulas and cached results", "显示公式及缓存结果"),
        "显示或隐藏没有本地改动的文件": ("Show or hide files without local changes", "显示或隐藏没有本地改动的文件"),
        "显示未修改文件": ("Show Unchanged Files", "显示未修改文件"),
        "显示未修改项": ("Show Unchanged", "显示未修改项"),
        "显示未纳入版本的文件": ("Show Unversioned Files", "显示未纳入版本的文件"),
        "更新": ("Update", "更新"),
        "更新 ": ("Updating ", "更新 "),
        "更新完成": ("Update complete", "更新完成"),
        "更新完成，正在刷新受影响文件…": ("Update complete; refreshing affected files…", "更新完成，正在刷新受影响文件…"),
        "更新范围：": ("Update scope: ", "更新范围："),
        "最小化": ("Minimize", "最小化"),
        "有冲突": ("Conflicted", "有冲突"),
        "未知": ("Unknown", "未知"),
        "未知作者": ("Unknown author", "未知作者"),
        "未知错误": ("Unknown error", "未知错误"),
        "未纳入版本": ("Unversioned", "未纳入版本"),
        "未选择单元格": ("No cell selected", "未选择单元格"),
        "未选择工作副本": ("No working copy selected", "未选择工作副本"),
        "本地忽略显示，不修改 SVN 属性": ("Hide locally without changing SVN properties", "本地忽略显示，不修改 SVN 属性"),
        "本地状态": ("Local State", "本地状态"),
        "本地目录名称": ("Local directory name", "本地目录名称"),
        "本地缺失": ("Missing", "本地缺失"),
        "本地预览": ("Local preview", "本地预览"),
        "查看属性": ("Show Properties", "查看属性"),
        "查看差异": ("Show Changes", "查看差异"),
        "查询": ("Query", "查询"),
        "标签与分支": ("Tag+Branch", "标签与分支"),
        "标记为删除？": ("Mark for Deletion?", "标记为删除？"),
        "标记删除…": ("Marking for deletion…", "标记删除…"),
        "格式": ("Format", "格式"),
        "检出…": ("Check Out…", "检出…"),
        "检出工作副本": ("Check Out Working Copy", "检出工作副本"),
        "检查改动": ("Check for Modifications", "检查改动"),
        "次要": ("Minor", "次要"),
        "正在加载 SVN…": ("Loading SVN…", "正在加载 SVN…"),
        "正在加载…": ("Loading…", "正在加载…"),
        "正在加载比较…": ("Loading comparison…", "正在加载比较…"),
        "正在合并变化并刷新界面…": ("Merging changes and refreshing the interface…", "正在合并变化并刷新界面…"),
        "正在整理目录和文件状态，请稍候…": ("Organizing directories and file status…", "正在整理目录和文件状态，请稍候…"),
        "正在检出…": ("Checking out…", "正在检出…"),
        "正常": ("Normal", "正常"),
        "此操作会丢弃本地修改，无法恢复。": ("This discards local changes and cannot be undone.", "此操作会丢弃本地修改，无法恢复。"),
        "此目录为空": ("This directory is empty", "此目录为空"),
        "比较 — ": ("Compare — ", "比较 — "),
        "没有匹配的文件": ("No matching files", "没有匹配的文件"),
        "没有可提交的改动": ("No changes to commit", "没有可提交的改动"),
        "添加": ("Add", "添加"),
        "添加工作副本": ("Add Working Copy", "添加工作副本"),
        "清理": ("Clean Up", "清理"),
        "清理工作副本…": ("Cleaning up working copy…", "清理工作副本…"),
        "清空输出": ("Clear Output", "清空输出"),
        "版本图": ("Graph", "版本图"),
        "界面语言": ("Interface Language", "界面语言"),
        "目录": ("Directories", "目录"),
        "相同": ("Same", "相同"),
        "相对目录": ("Relative Directory", "相对目录"),
        "确定": ("OK", "确定"),
        "确认": ("Confirm", "确认"),
        "移动": ("Move", "移动"),
        "移动…": ("Moving…", "移动…"),
        "移动或重命名": ("Move or Rename", "移动或重命名"),
        "移动或重命名…": ("Move or Rename…", "移动或重命名…"),
        "移除": ("Remove", "移除"),
        "移除版本控制…": ("Removing from version control…", "移除版本控制…"),
        "窗口": ("Window", "窗口"),
        "筛选修订号、作者和说明": ("Filter revisions, authors and messages", "筛选修订号、作者和说明"),
        "管理忽略项": ("Manage Hidden Items", "管理忽略项"),
        "管理忽略项…": ("Manage Hidden Items…", "管理忽略项…"),
        "粘贴": ("Paste", "粘贴"),
        "统一差异": ("Unified", "统一差异"),
        "继续": ("Continue", "继续"),
        "编辑": ("Edit", "编辑"),
        "缩放": ("Zoom", "缩放"),
        "被阻挡": ("Obstructed", "被阻挡"),
        "规则": ("Rules", "规则"),
        "视图": ("View", "视图"),
        "解决冲突…": ("Resolving conflict…", "解决冲突…"),
        "解锁": ("Unlock", "解锁"),
        "解锁文件…": ("Unlocking files…", "解锁文件…"),
        "设置…": ("Settings…", "设置…"),
        "该操作会立即在仓库中创建一次提交。": ("This operation immediately creates a commit in the repository.", "该操作会立即在仓库中创建一次提交。"),
        "该目录没有可显示的文本或属性差异。子项变化请在文件列表中选择。": ("This directory has no textual or property differences. Select files in the list to compare descendants.", "该目录没有可显示的文本或属性差异。子项变化请在文件列表中选择。"),
        "语言": ("Language", "语言"),
        "说明": ("Message", "说明"),
        "请先勾选文件": ("Please select files first", "请先勾选文件"),
        "请先在文件列表中选择一个文件": ("Please select a file in the list first", "请先在文件列表中选择一个文件"),
        "请先将未纳入版本的文件加入版本控制": ("Add unversioned files to version control first", "请先将未纳入版本的文件加入版本控制"),
        "请先打开工作副本": ("Please open a working copy first", "请先打开工作副本"),
        "请先打开或检出一个 SVN 工作副本": ("Open or check out an SVN working copy first", "请先打开或检出一个 SVN 工作副本"),
        "请填写提交说明": ("Please enter a commit message", "请填写提交说明"),
        "请输入合并来源 URL": ("Merge source URL is required", "请输入合并来源 URL"),
        "请输入有效仓库 URL 和 HEAD 或非负修订号。": ("Enter a valid repository URL and HEAD or a nonnegative revision.", "请输入有效仓库 URL 和 HEAD 或非负修订号。"),
        "读取仓库…": ("Reading repository…", "读取仓库…"),
        "读取属性…": ("Reading properties…", "读取属性…"),
        "读取工作表并比较…": ("Reading and comparing worksheets…", "读取工作表并比较…"),
        "读取提交历史…": ("Reading history…", "读取提交历史…"),
        "读取文件历史…": ("Reading file history…", "读取文件历史…"),
        "路径": ("Path", "路径"),
        "输入 SVN 仓库 URL": ("Enter an SVN repository URL", "输入 SVN 仓库 URL"),
        "输入仓库 URL 开始浏览": ("Enter a repository URL to browse", "输入仓库 URL 开始浏览"),
        "输入提交说明": ("Enter a commit message", "输入提交说明"),
        "输入目标仓库 URL，将从当前工作副本地址执行服务器端复制。": ("Enter the destination repository URL to create a server-side copy of this working copy URL.", "输入目标仓库 URL，将从当前工作副本地址执行服务器端复制。"),
        "输入目标分支或标签 URL。执行前请先提交或搁置本地改动。": ("Enter the target branch or tag URL. Commit or shelve local changes before switching.", "输入目标分支或标签 URL。执行前请先提交或搁置本地改动。"),
        "输入相对于工作副本的新路径": ("Enter a new path relative to the working copy", "输入相对于工作副本的新路径"),
        "输出": ("Output", "输出"),
        "进入全屏幕": ("Enter Full Screen", "进入全屏幕"),
        "远程状态": ("Remote State", "远程状态"),
        "退出全屏幕": ("Exit Full Screen", "退出全屏幕"),
        "选择一条修订记录": ("Select a revision", "选择一条修订记录"),
        "选择文件查看差异": ("Select a file to view changes", "选择文件查看差异"),
        "选择父目录": ("Choose Parent Directory", "选择父目录"),
        "逐行追溯": ("Annotate", "逐行追溯"),
        "逐行追溯…": ("Annotating…", "逐行追溯…"),
        "重做": ("Redo", "重做"),
        "重新加载": ("Retry loading", "重新加载"),
        "重新加载差异": ("Reload Changes", "重新加载差异"),
        "重载": ("Reload", "重载"),
        "锁定": ("Lock", "锁定"),
        "锁定文件…": ("Locking files…", "锁定文件…"),
        "锁定管理": ("Locks", "锁定管理"),
        "项目": ("Project", "项目"),
        "预演合并…": ("Previewing merge…", "预演合并…"),
        "｜只读 · 禁止编辑": ("Read only · Editing disabled", "｜只读 · 禁止编辑"),
    ]
}
struct LanguageMenu: View {
    @AppStorage(InterfaceLanguage.key) private var language = "zh-Hans"
    var body: some View {
        Menu {
            Button { InterfaceLanguage.select("zh-Hans") } label: { Label("简体中文", systemImage: language == "zh-Hans" ? "checkmark" : "") }
            Button { InterfaceLanguage.select("en") } label: { Label("English", systemImage: language == "en" ? "checkmark" : "") }
        } label: { Label(L("Language"), systemImage: "globe") }
    }
}
struct LanguageSettings: View {
    @AppStorage(InterfaceLanguage.key) private var language = "zh-Hans"
    var body: some View {
        Form {
            Picker(L("Interface Language"), selection: Binding(get: { language }, set: { InterfaceLanguage.select($0) })) {
                Text("简体中文").tag("zh-Hans")
                Text("English").tag("en")
            }
            Text(L("Language changes apply immediately and are remembered on this Mac.")).foregroundStyle(WorkbenchTheme.muted)
        }.padding(24).frame(width: 440, height: 130).workbenchStyle()
    }
}

func T(_ english: String, _ chinese: String, _ values: Any...) -> String {
    let template = InterfaceLanguage.code == "en" ? english : chinese
    let result = NSMutableString(string: template)
    let regex = try! NSRegularExpression(pattern: "\\{([0-9]+)\\}")
    for match in regex.matches(in: template, range: NSRange(location: 0, length: (template as NSString).length)).reversed() {
        let index = Int((template as NSString).substring(with: match.range(at: 1)))!
        if values.indices.contains(index) { result.replaceCharacters(in: match.range, with: String(describing: values[index])) }
    }
    return result as String
}

@MainActor private func localizedWindowTitle(_ title: String) -> String {
    if title.hasSuffix("设置") || title == "SVN Workbench Settings" { return AppIdentity.name + T(" Settings", "设置") }
    for (en, zh) in [("Compare — ", "比较 — "), ("Log — ", "日志 — "), ("Directory Changes — ", "目录差异 — ")] {
        for source in [en, zh] where title.hasPrefix(source) { return (InterfaceLanguage.code == "en" ? en : zh) + title.dropFirst(source.count) }
    }
    for source in [" — Table Compare", " — 表格比较"] where title.hasSuffix(source) {
        return title.dropLast(source.count) + T(" — Table Compare", " — 表格比较")
    }
    return L(title)
}
@MainActor func localizeSystemMenus() {
    guard let menu = NSApp.mainMenu else { return }
    func visit(_ menu: NSMenu, top: Bool) {
        for item in menu.items {
            if top && item.title == "显示" { item.title = T("View", "显示") }
            else if top && ["File", "文件", "Files"].contains(item.title) { item.title = T("File", "文件") }
            else { item.title = L(item.title) }
            if let submenu = item.submenu { submenu.title = item.title; visit(submenu, top: false) }
        }
    }
    visit(menu, top: true)
}
